"""hashed_passwd

Revision ID: e524f85a240c
Revises: 7277edfccf21
Create Date: 2022-10-29 13:00:10.216999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e524f85a240c'
down_revision = '7277edfccf21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('picture_path', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['picture_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'picture_path')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
