version: "3.8"

services:
  backend:
    image: platform_api
    command: uvicorn --reload --host 0.0.0.0 --port 8000 platform_api.main:app
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db/platform_api_db"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: platform_api_db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "platform_api_db"]
      interval: 10s
      timeout: 5s
      retries: 5
